### ISSUE TITLE
Plugin 'mark tier relations' fails if there are more than one TextGrid files

### ISSUE THREAD

**Issue by yqzhishen** [sdercolin/vlabeler-textgrid#1]
The plugin 'mark tier relations' always fails on my computer if there are more than one TextGrid files in one project, even if it can succeed on either of the TextGrid file.

## To reproduce

[opencpop_vlabeler_test.zip](https://github.com/sdercolin/vlabeler-textgrid/files/12305627/opencpop_vlabeler_test.zip)

The above are two recordings from the opencpop dataset, and their corresponding TextGrids containing three tiers named words, notes and phones. I tried to create project on each of them (so that the project contains only one item), the plugin could succeed; but when I put the two items in one project, the plugin failed.

<img width="505" alt="image" src="https://github.com/sdercolin/vlabeler-textgrid/assets/70186231/003d41b4-34e3-4598-a35c-f5115314ac1b">

**Comment by sdercolin** [comment]
Thank you for the report.
Could you please try this edted script?
[textgrid-mark-tier-relations.js.zip](https://github.com/sdercolin/vlabeler-textgrid/files/12308664/textgrid-mark-tier-relations.js.zip)

**Comment by yqzhishen** [comment]
It works now, thanks!

But I got another question: is the plugin 'merge to update next tier' performed only on the currently editing item? I ran this plugin and the tiers of the other item in my project did not get updated; but when I switched to the other item and ran the plugin again, the tiers got updated as normal. I wonder if this is a bug or the expected behavior, but I want that plugin to do batch editing.

**Comment by sdercolin** [comment]
In your case we have the tier structure like `phones` > `notes` > `words`.

Currently when you are editing `phones` , this plugin only update its next (direct parent) tier which is `notes`, so you may need to switch to `notes` tier and run the plugin again, so that `words` is also updated.

Is this what you mean? If so, yes, this is the current behavior. (but we can later make it able to do it recursively)

If you mean `entry` by `item`, that should be a bug, because this plugin should handle all entries in the tier. In this case we may need some more info to reproduce it.

**Comment by sdercolin** [comment]
https://github.com/sdercolin/vlabeler-textgrid/assets/7665216/180294ea-c7f5-42ef-b75a-8ad16068d9c3

Not related but I found it inconvenient when editing your project because there are short entries at the beginning, so I improved the module label like this. If you have any suggestions about it please let me know

**Comment by yqzhishen** [comment]
Sorry, I didn't described it clearly. When I said "item" I mean "one TextGrid file". When I ran the plugin on one TextGrid, the other TextGrid didn't get updated.

**Comment by sdercolin** [comment]
Oh okay, right, the current behavior only handles the current tab(=module=sub-project). But we can add options to 
- [ ] handle all modules with the same tier name
- [ ] merge recursively to other tiers

**Comment by yqzhishen** [comment]
yes the changes you suggested/shown above will make the software much easier to use.

By the way, do you think it is reasonable to have an _inverse_ operation of this? For example, if I dragged the boundary of a "word", I may also expect the boundaries of its first/last child "note" to be aligned with it. I have a "notes>words,phones>words" relation where one tier have two children tiers, so this feature will help me a lot.

However, probably the more direct way is to let the close (aligned) boundaries be dragged together, despite how their relations are. Praat has this feature (pressing `Shift`), but I think the more convenient logic is to make it default.

**Comment by sdercolin** [comment]
> However, probably the more direct way is to let the close (aligned) boundaries be dragged together, despite how their relations are. Praat has this feature (pressing Shift), but I think the more convenient logic is to make it default.

Yes I think this makes sense and will be helpful, but it's a bit difficult to implement. I will add it to the roadmap, but I am not sure when I could finish it.

Currently you may find the snap-drag helpful (when you drag a line it will be snapped to align with a line in other tiers).
See [tips](https://github.com/sdercolin/vlabeler-textgrid#tips) 3 and 4.

**Comment by yqzhishen** [comment]
Okay, thanks! Looking forward to future updates.

**Comment by sdercolin** [comment]
@yqzhishen I have published a new release, please have a try with the new features!
